# .readthedocs.yaml
# Read the Docs config file
# 
version: 2

# set the OS, python versions needed and other tools needed
build: 
  os: ubuntu-22.04
    tools:
      python: "3.12"
# build documentation in 'docs/' dir w sphinx
sphinx: 
  configuration: docs/conf.py

formats:
  - pdf
  - epub
python:
  install:
  - requirements: docs/requirements.txt
