name: itslivetools
channels:
  - conda-forge
  - fastai
dependencies:
  - beautifulsoup4~=4.12
  - dask~=2023.7
  - geopandas~=0.13
  - jupyterlab~=3.6
  - ipyleaflet~=0.17
  - ipywidgets~=8.0
  - matplotlib~=3.7
  - fastai::nbdev~=2.3
  - numpy~=1.23
  - owslib~=0.29
  - pandas~=1.5
  - pyproj~=3.6
  - requests~=2.31
  - rioxarray~=0.14
  - s3fs~=2023.6
  - scikit-learn~=1.2
  - scipy~=1.10
  - setuptools~=68.2
  - shapely~=2.0
  - pytorch~=2.1
  - tqdm~=4.65.0
  - xarray~=2023.7.0
  - zarr~=2.15.0
platforms:
  - osx-64
  - linux-64

